/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->Delay1_DSTATE);
   memcpy(&pDst->Delay1_DSTATE, &pSrc->Delay1_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->StateSpace_DSTATE);
   memcpy(&pDst->StateSpace_DSTATE, &pSrc->StateSpace_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay4_DSTATE);
   memcpy(&pDst->UnitDelay4_DSTATE, &pSrc->UnitDelay4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE);
   memcpy(&pDst->Integ4_DSTATE, &pSrc->Integ4_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE);
   memcpy(&pDst->UnitDelay_DSTATE, &pSrc->UnitDelay_DSTATE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_a);
   memcpy(&pDst->Integ4_DSTATE_a, &pSrc->Integ4_DSTATE_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_b);
   memcpy(&pDst->UnitDelay_DSTATE_b, &pSrc->UnitDelay_DSTATE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_e);
   memcpy(&pDst->Integ4_DSTATE_e, &pSrc->Integ4_DSTATE_e, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_n);
   memcpy(&pDst->UnitDelay_DSTATE_n, &pSrc->UnitDelay_DSTATE_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_DSTATE_l);
   memcpy(&pDst->Integ4_DSTATE_l, &pSrc->Integ4_DSTATE_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->UnitDelay_DSTATE_h);
   memcpy(&pDst->UnitDelay_DSTATE_h, &pSrc->UnitDelay_DSTATE_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput);
   memcpy(&pDst->Memory_PreviousInput, &pSrc->Memory_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_d);
   memcpy(&pDst->Memory_PreviousInput_d, &pSrc->Memory_PreviousInput_d, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_g);
   memcpy(&pDst->Memory_PreviousInput_g, &pSrc->Memory_PreviousInput_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_l);
   memcpy(&pDst->Memory_PreviousInput_l, &pSrc->Memory_PreviousInput_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_f);
   memcpy(&pDst->Memory_PreviousInput_f, &pSrc->Memory_PreviousInput_f, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_da);
   memcpy(&pDst->Memory_PreviousInput_da, &pSrc->Memory_PreviousInput_da, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Memory_PreviousInput_i);
   memcpy(&pDst->Memory_PreviousInput_i, &pSrc->Memory_PreviousInput_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK);
   memcpy(&pDst->TransportDelay_RWORK, &pSrc->TransportDelay_RWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_h);
   memcpy(&pDst->TransportDelay_RWORK_h, &pSrc->TransportDelay_RWORK_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_n);
   memcpy(&pDst->TransportDelay_RWORK_n, &pSrc->TransportDelay_RWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_hd);
   memcpy(&pDst->TransportDelay_RWORK_hd, &pSrc->TransportDelay_RWORK_hd, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_n2);
   memcpy(&pDst->TransportDelay_RWORK_n2, &pSrc->TransportDelay_RWORK_n2, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_j);
   memcpy(&pDst->TransportDelay_RWORK_j, &pSrc->TransportDelay_RWORK_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_RWORK_ju);
   memcpy(&pDst->TransportDelay_RWORK_ju, &pSrc->TransportDelay_RWORK_ju, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->StateSpace_IWORK);
   memcpy(&pDst->StateSpace_IWORK, &pSrc->StateSpace_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK);
   memcpy(&pDst->TransportDelay_IWORK, &pSrc->TransportDelay_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_n);
   memcpy(&pDst->TransportDelay_IWORK_n, &pSrc->TransportDelay_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_p);
   memcpy(&pDst->TransportDelay_IWORK_p, &pSrc->TransportDelay_IWORK_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_b);
   memcpy(&pDst->TransportDelay_IWORK_b, &pSrc->TransportDelay_IWORK_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_k);
   memcpy(&pDst->SFunction_IWORK_k, &pSrc->SFunction_IWORK_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_n);
   memcpy(&pDst->SFunction_IWORK_n, &pSrc->SFunction_IWORK_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_g);
   memcpy(&pDst->SFunction_IWORK_g, &pSrc->SFunction_IWORK_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK_ka);
   memcpy(&pDst->SFunction_IWORK_ka, &pSrc->SFunction_IWORK_ka, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_o);
   memcpy(&pDst->TransportDelay_IWORK_o, &pSrc->TransportDelay_IWORK_o, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_ns);
   memcpy(&pDst->TransportDelay_IWORK_ns, &pSrc->TransportDelay_IWORK_ns, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TransportDelay_IWORK_bl);
   memcpy(&pDst->TransportDelay_IWORK_bl, &pSrc->TransportDelay_IWORK_bl, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE, &pSrc->Integ4_SYSTEM_ENABLE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_b);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_b, &pSrc->Integ4_SYSTEM_ENABLE_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_g);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_g, &pSrc->Integ4_SYSTEM_ENABLE_g, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Integ4_SYSTEM_ENABLE_bk);
   memcpy(&pDst->Integ4_SYSTEM_ENABLE_bk, &pSrc->Integ4_SYSTEM_ENABLE_bk, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->TrueRMS_MODE);
   memcpy(&pDst->TrueRMS_MODE, &pSrc->TrueRMS_MODE, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RMS_MODE);
   memcpy(&pDst->RMS_MODE, &pSrc->RMS_MODE, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick1);
   memcpy(&pDst->Timing.clockTick1, &pSrc->Timing.clockTick1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH1);
   memcpy(&pDst->Timing.clockTickH1, &pSrc->Timing.clockTickH1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize1);
   memcpy(&pDst->Timing.stepSize1, &pSrc->Timing.stepSize1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.CTOutputIncnstWithState);
   memcpy(&pDst->ModelData.CTOutputIncnstWithState, &pSrc->ModelData.CTOutputIncnstWithState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeF);
   memcpy(&pDst->ModelData.odeF, &pSrc->ModelData.odeF, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeY);
   memcpy(&pDst->ModelData.odeY, &pSrc->ModelData.odeY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

