/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->INPUT_1_1_1_Discrete);
   memcpy(&pDst->INPUT_1_1_1_Discrete, &pSrc->INPUT_1_1_1_Discrete, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_Discrete);
   memcpy(&pDst->STATE_1_Discrete, &pSrc->STATE_1_Discrete, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_Discrete);
   memcpy(&pDst->OUTPUT_1_0_Discrete, &pSrc->OUTPUT_1_0_Discrete, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RTP_1_RtpManager);
   memcpy(&pDst->RTP_1_RtpManager, &pSrc->RTP_1_RtpManager, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_Simulator);
   memcpy(&pDst->STATE_1_Simulator, &pSrc->STATE_1_Simulator, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_SimData);
   memcpy(&pDst->STATE_1_SimData, &pSrc->STATE_1_SimData, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_DiagMgr);
   memcpy(&pDst->STATE_1_DiagMgr, &pSrc->STATE_1_DiagMgr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_ZcLogger);
   memcpy(&pDst->STATE_1_ZcLogger, &pSrc->STATE_1_ZcLogger, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_TsIndex);
   memcpy(&pDst->STATE_1_TsIndex, &pSrc->STATE_1_TsIndex, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_Simulator);
   memcpy(&pDst->OUTPUT_1_0_Simulator, &pSrc->OUTPUT_1_0_Simulator, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_SimData);
   memcpy(&pDst->OUTPUT_1_0_SimData, &pSrc->OUTPUT_1_0_SimData, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_DiagMgr);
   memcpy(&pDst->OUTPUT_1_0_DiagMgr, &pSrc->OUTPUT_1_0_DiagMgr, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_ZcLogger);
   memcpy(&pDst->OUTPUT_1_0_ZcLogger, &pSrc->OUTPUT_1_0_ZcLogger, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_TsIndex);
   memcpy(&pDst->OUTPUT_1_0_TsIndex, &pSrc->OUTPUT_1_0_TsIndex, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_Modes);
   memcpy(&pDst->STATE_1_Modes, &pSrc->STATE_1_Modes, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_Modes);
   memcpy(&pDst->OUTPUT_1_0_Modes, &pSrc->OUTPUT_1_0_Modes, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RTP_1_SetParametersNeeded);
   memcpy(&pDst->RTP_1_SetParametersNeeded, &pSrc->RTP_1_SetParametersNeeded, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->STATE_1_FirstOutput);
   memcpy(&pDst->STATE_1_FirstOutput, &pSrc->STATE_1_FirstOutput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->OUTPUT_1_0_FirstOutput);
   memcpy(&pDst->OUTPUT_1_0_FirstOutput, &pSrc->OUTPUT_1_0_FirstOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick1);
   memcpy(&pDst->Timing.clockTick1, &pSrc->Timing.clockTick1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH1);
   memcpy(&pDst->Timing.clockTickH1, &pSrc->Timing.clockTickH1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize1);
   memcpy(&pDst->Timing.stepSize1, &pSrc->Timing.stepSize1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.CTOutputIncnstWithState);
   memcpy(&pDst->ModelData.CTOutputIncnstWithState, &pSrc->ModelData.CTOutputIncnstWithState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeF);
   memcpy(&pDst->ModelData.odeF, &pSrc->ModelData.odeF, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.odeY);
   memcpy(&pDst->ModelData.odeY, &pSrc->ModelData.odeY, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

